### ISSUE TITLE
`table-layout:auto` for documentation

### ISSUE THREAD

**Issue by ru-fu** [canonical/anbox-cloud.io#273]
By default, Vanilla uses `table-layout:fixed` - which might make pages render a little faster, but it's usually not suitable for documentation.

For example, this is how [one of our tables](https://anbox-cloud.io/docs/ref/provided-images) looks with fixed layout:
![table-layout-fixed](https://user-images.githubusercontent.com/11227796/205072934-8d4635e1-8630-4ec3-aba5-c492ffcdc033.png)

Here's how it would look with `auto` layout:
![table-layout-auto](https://user-images.githubusercontent.com/11227796/205073062-1dc9cb59-78e3-4637-ae7c-e2b12b3c78e3.png)

Unfortunately, it doesn't seem to be possible to pass through CSS classes or styles by adding HTML code to Discourse. So the only way to fix this is probably to set the `$table-layout-fixed` to `false` for the full docs.

See also https://github.com/canonical/vanilla-framework/issues/2374

**Comment by evilnick** [comment]
For context, this is the case across all docs. I can't think of a single instance of a table in documentation which we would actually want to follow a fixed width style.
